### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by movieator** [rikulo/socket.io-dart#11]
Hi, I' m using socket_io: ^0.9.0+2 and socket_io_client: ^0.9.4 in my pubspec.yaml file.
When i run my app, i'm getting the following error:

Resolving dependencies...                                           2,9s
Error reading dependency file D:\Source\Flutter\Mobile\aiqueue\build\app\intermediates\flutter\debug\android-arm\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
Error reading dependency file D:\Source\Flutter\Mobile\aiqueue\build\app\intermediates\flutter\debug\android-arm\snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1

Compiler message:
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/rikulo_commons-3.2.1/lib/src/io/http_wrapper.dart:9:7: Error: 'HttpRequestWrapper' can't implement both 'Stream<List<int>>' and 'Stream<Uint8List>'
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
class HttpRequestWrapper extends StreamWrapper<List<int>> implements HttpRequest {
      ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/stream-2.2.1/lib/src/connect_impl.dart:249:7: Error: '_ReUriRequest' can't implement both 'Stream<List<int>>' and 'Stream<Uint8List>'
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'Uint8List' is from 'dart:typed_data'.
class _ReUriRequest extends HttpRequestWrapper {
      ^
Compiler failed on D:\Source\Flutter\Mobile\aiqueue\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

**My flutter doctor results:**

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.10.1, on Microsoft Windows [Version 10.0.17763.737], locale el-GR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.38.0)
[√] Connected device (1 available)

• No issues found!

**Comment by SimchaCahn** [comment]
Did you end up finding a solution to this issue?

**Comment by MrCreeper1008** [comment]
Same. This has never happened before until today.

**Comment by jumperchen** [comment]
It's related to the issue - https://github.com/rikulo/commons/commit/aa4c847cc08569298b8ea86649d12ca75866d9a0
After upgrading [rikulo_commons](https://github.com/rikulo/commons) version `3.2.1+1` should fix this issue.
Any of you can test it for me?

**Comment by MrCreeper1008** [comment]
I’ll test it today. Thanks!
