### ISSUE TITLE
Exception after a large number of failed connection attempts

### ISSUE THREAD

**Issue by JonHodgson** [rikulo/socket.io-dart#12]
If I run my angular application without my server running, it continues to attempt to reconnect until I start my server, which is as expected.
But if I don't start my server (my application can mostly function without it) then after a long period of time (I haven't timed it since it tends to happen when my computer is unattended, but I think several hours), there is an exception.

`dart_sdk.js:98521 EXCEPTION: Unsupported operation: Infinity
STACKTRACE: 
dart:sdk_internal 11192:44                                                         floor]
package:socket_io_client/src%5Cmanager.dart 576:43                                 get duration
package:socket_io_client/src%5Cmanager.dart 494:32                                 reconnect
package:socket_io_client/src%5Cmanager.dart 512:13                                 <fn>
dart:sdk_internal 4077:17                                                          dcall
package:socket_io_client/src%5Cmanager.dart 233:17                                 <fn>
dart:sdk_internal 4077:17                                                          dcall
package:socket_io_common/src%5Cutil%5Cevent_emitter.dart 52:14                     <fn>
dart:sdk_internal 10516:11                                                         forEach]
package:socket_io_common/src%5Cutil%5Cevent_emitter.dart 51:11                     emit
package:socket_io_client/src%5Cengine%5Csocket.dart 692:10                         onError
package:socket_io_client/src%5Cengine%5Csocket.dart 307:28                         <fn>
dart:sdk_internal 4077:17                                                          dcall
package:socket_io_common/src%5Cutil%5Cevent_emitter.dart 52:14                     <fn>
dart:sdk_internal 10516:11                                                         forEach]
package:socket_io_common/src%5Cutil%5Cevent_emitter.dart 51:11                     emit
package:socket_io_client/src%5Cengine%5Ctransport%5Ctransport.dart 64:12           onError
package:socket_io_client/src%5Cengine%5Ctransport%5Cwebsocket_transport.dart 68:9  <fn>
dart:sdk_internal 96016:96                                                         <fn>
package:angular/src/core/change_detection/..%5Czone%5Cng_zone.dart 156:18          <fn>
dart:sdk_internal 30751:14                                                         runUnary
package:angular/src/core/change_detection/..%5Czone%5Cng_zone.dart 153:18          [_runUnary]
dart:sdk_internal 31004:34                                                         <fn>
`

**Comment by jumperchen** [comment]
It's an issue of socket.io-client-dart - https://github.com/rikulo/socket.io-client-dart/issues/39
