### ISSUE TITLE
How does this get a list of clients if it doesn't return a List?

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [rikulo/socket.io-dart#14]
https://github.com/rikulo/socket.io-dart/blob/7fdb7602fc68fc9e859a41694fa685692244db2c/lib/src/namespace.dart#L223-L233

**Comment by jumperchen** [comment]
The api usage likes this.
```
foo.clients((sids) {
   // the sids here is a list of sockets' id
});
```

You can take a look at - https://github.com/rikulo/socket.io-dart/blob/8b05ec85a673ebaa0f7406a2bed77f76d8224e56/lib/src/adapter/adapter.dart#L194

**Comment by ThinkDigitalSoftware** [comment]
So does the documentation for this function need to be updated or is it fine?

**Comment by jumperchen** [comment]
according to the JS implementation here - https://github.com/socketio/socket.io-adapter/blob/master/index.js#L166
I think it's fine so far. :)
