### ISSUE TITLE
 Dart Error: error: import of dart:mirrors is not supported in the current Dart runtime

### ISSUE THREAD

**Issue by ZangTengfei** [rikulo/socket.io-dart#21]
After import 'package:socket_io/socket_io.dart', This error occurred

**Comment by jumperchen** [comment]
this is a server side library, so are you looking for https://github.com/rikulo/socket.io-client-dart ?

**Comment by ZangTengfei** [comment]
> this is a server side library, so are you looking for https://github.com/rikulo/socket.io-client-dart ?

Oh i see,tks
