### ISSUE TITLE
secure connection from client

### ISSUE THREAD

**Issue by u007** [rikulo/socket.io-dart#25]
hi,

is it possible to connect securely from client via https?
or can we connect via client with secure:true and proxy via caddy or nginx to non secure server?

thank you

**Comment by jumperchen** [comment]
Yes, it should be possible to connect from client via https.

**Comment by u007** [comment]
hi what is the correct way to connect from client side?

**Comment by jumperchen** [comment]
FYI:https://github.com/rikulo/socket.io-client-dart/issues/30#issuecomment-517520008
