### ISSUE TITLE
I can't connect to http server with this package in iOS.

### ISSUE THREAD

**Issue by ryz418** [rikulo/socket.io-dart#29]
IO.Socket socket = IO.io('http://94.130.180.124:8080/', <String, dynamic>{
      'transports': ['websocket'],
      'autoConnect': true,
    });

void testSocket(){
  socket.connect();
  print('Socket connected');
  socket.emit('test', 'Socket test');
  socket.on('received_test', (data){
    print('--Test received--');
    print(data);
  })
}
when I use http://localhost:8080/ , socket is working well.
But when I use http://94.130.180.124:8080/, I can't receive response data.

Backend source code of above two links are same.
Please help me.

**Comment by jumperchen** [comment]
Are you talking about [socket.io-client-dart](https://github.com/rikulo/socket.io-client-dart) or socket.io Server (this repo.)?

**Comment by ryz418** [comment]
> Are you talking about [socket.io-client-dart](https://github.com/rikulo/socket.io-client-dart) or socket.io Server (this repo.)?

I am taking about socket_io_client package,
