### ISSUE TITLE
Would this work with flutter?

### ISSUE THREAD

**Issue by RashadSaleh** [rikulo/socket.io-dart#3]
Would this work with flutter for making mobile apps?

**Comment by jumperchen** [comment]
This project is a server side implementation, so are you looking for [socket.io-client-dart](https://github.com/rikulo/socket.io-client-dart/issues/4)?

**Comment by kdy1** [comment]
@jumperchen I want to use this library while testing, but `flutter test` emits an error.

```
Dart Error: error: import of dart:mirrors with --enable-mirrors=false
```

**Comment by jumperchen** [comment]
Please use [socket.io-client-dart](https://github.com/rikulo/socket.io-client-dart/issues/4), this project is a socket.io server.
