### ISSUE TITLE
Flutter mobile app socket connection issue

### ISSUE THREAD

**Issue by shubhamssinghal** [rikulo/socket.io-dart#30]
Hi 

I am using **socket_io_client** library in my flutter mobile app to build chat app. I am able to connect and chat with socket connection with local url but when I use development url it gives below error in socket.OnConnectionError - 

**WebSocketException: Connection to 'http://x.xxx.xxx.xx:0/socket.io/?EIO=3&transport=websocket#' was not upgraded to websocket**

Please help me out.I am stuck at this

Thank you

**Comment by jumperchen** [comment]
please post issue to https://github.com/rikulo/socket.io-client-dart, here is for socket.io server.
