### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by TimWhiting** [rikulo/socket.io-dart#33]
Would love to see a null safe version of this library. If I have some time I'll look into a PR.

**Comment by TimWhiting** [comment]
Looks like this is blocked on rikulo/commons and rikulo/stream

**Comment by mavyfaby** [comment]
Any updates?

**Comment by mavyfaby** [comment]
Any latest updates?

**Comment by TimWhiting** [comment]
rikulo/commons and rikulo/stream have been migrated thanks to @tomyeh This should be unblocked for migration.
