### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by mavyfaby** [rikulo/socket.io-dart#35]
Hello,

I would like to ask if when is the next version for this library for Flutter 2.x null-safety support.

**Comment by jumperchen** [comment]
Using this library in Flutter as socket server?

**Comment by mavyfaby** [comment]
Yes, I would like to contribute but I don't know how to migrate a non-null-safety library to null-safety.

**Comment by jumperchen** [comment]
Duplicated as https://github.com/rikulo/socket.io-dart/issues/33
