### ISSUE TITLE
Can't add both server and client library.

### ISSUE THREAD

**Issue by mavyfaby** [rikulo/socket.io-dart#37]
```
Running "flutter pub get" in Example...  
                      
Because socket_io_client >=2.0.0-beta.3-nullsafety.0 depends on socket_io_common ^2.0.0-beta.1-nullsafety.0 and socket_io 1.0.0 depends on socket_io_common ^1.0.0-nullsafety.1, socket_io_client >=2.0.0-beta.3-nullsafety.0 is incompatible with socket_io 1.0.0.
And because no versions of socket_io match >1.0.0 <2.0.0, socket_io_client >=2.0.0-beta.3-nullsafety.0 is incompatible with socket_io ^1.0.0.
So, because nearline depends on both socket_io ^1.0.0 and socket_io_client ^2.0.0-beta.3-nullsafety.0, version solving failed.
```

Both server and client libraries depends on `socket_io_common` with different versions.

**Comment by mavyfaby** [comment]
@jumperchen

**Comment by jumperchen** [comment]
They are different Socket.io spec. versions (v2 vs v3), you cannot use them together, the `socket_io` server is based on Socket.io **v2** but `sockert_io_client` `v2.0.0*` is based on Sockert.io **v3** spec, you need to use `v1.0.0*` for `sockert_io_client`.

**Comment by mavyfaby** [comment]
Is there any other way to use them together?

**Comment by jumperchen** [comment]
FYI: https://pub.dev/packages/socket_io_client/versions/1.0.0-nullsafety.0
