### ISSUE TITLE
Integration with Alfred Framework

### ISSUE THREAD

**Issue by Donk3ys** [rikulo/socket.io-dart#40]
Ive been trying to integrate the socket_io package with [alfred](https://github.com/rknell/alfred) but socket_io seems to only allow StreamServers and Alfred implements HttpServer.

Has anyone found a way to integrate both?

**Comment by Levyks** [comment]
Any updates? I was trying to do the same thing

**Comment by akram-95** [comment]
You can this plugin https://github.com/Fennec-Framework/fennec_socket_io_server
