### ISSUE TITLE
Use with webserver

### ISSUE THREAD

**Issue by FancyPlants** [rikulo/socket.io-dart#6]
Is there any way to attach this to say, a shelf instance? I want to be able to serve the SPA to the client while also simultaneously handling Socket.IO traffic.

**Comment by jumperchen** [comment]
Yes, you can pass a [StreamServer](https://github.com/rikulo/stream) to it, like this line. - https://github.com/rikulo/socket.io-dart/blob/master/lib/src/server.dart#L54

**Comment by FancyPlants** [comment]
Cool, thank you
